---
services:
  scripts:
    container_name: aws_usage_cost
    # image: aws_usage_cost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_CREDENTIALS=${N8N_CREDENTIALS}
      - HEALTHCHECKS_URL_AWS_USAGE_COST=${HEALTHCHECKS_URL_AWS_USAGE_COST}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - THRESHOLD=5
    network_mode: host
